version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: playground
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playground-nestjs
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.stage.build
    depends_on:
      - postgres

volumes:
  postgres_data: